import type { Asset } from './types'

export const MOCK_ASSETS: Asset[] = [
  {
    id: '1',
    tag: '3113-10-00-11-BLG0002',
    nombre: 'Edificio Truckshop',
    tipo: 'Edificio',
    capa: 'superficie',
    sector: 'superficie',
    lat: -46.863662843262944,
    lng: -70.32678287840358,
    status: 'Operativo',
    estado: 'Óptimo',
    ubicacion: 'Sector Talleres',
    inspector_asignado: 'M. Rodríguez',
    ultima_inspeccion: '2025-04-10',
    proxima_inspeccion: '2025-07-10',
    checklist: [
      { descripcion: 'Estructura principal — fisuras visibles', resultado: true },
      { descripcion: 'Puertas y portones — operatividad',       resultado: true },
      { descripcion: 'Drenajes pluviales',                      resultado: false, nota: 'Canaleta tapada sector N' },
      { descripcion: 'Señalética de seguridad',                 resultado: true },
    ],
    historial: [
      { fecha: '2025-04-10', texto: 'Inspección rutinaria — drenaje N observado', estado: 'warn' },
      { fecha: '2025-01-08', texto: 'Inspección trimestral sin hallazgos',         estado: 'ok' },
    ],
  },
  {
    id: '2',
    tag: '3113-10-00-11-SCL0001',
    nombre: 'Báscula camiones',
    tipo: 'Equipo industrial',
    capa: 'superficie',
    sector: 'superficie',
    lat: -46.8641,
    lng: -70.3261,
    status: 'En mantenimiento',
    estado: 'Sello deteriorado',
    ubicacion: 'Acceso principal',
    inspector_asignado: 'P. González',
    ultima_inspeccion: '2025-03-20',
    proxima_inspeccion: '2025-06-20',
    checklist: [
      { descripcion: 'Plataforma — nivelación',        resultado: true },
      { descripcion: 'Celdas de carga — calibración',  resultado: true },
      { descripcion: 'Sellados antihumedad',            resultado: false, nota: 'Sello lateral derecho deteriorado' },
    ],
    historial: [
      { fecha: '2025-03-20', texto: 'Sello lateral a reparar', estado: 'warn' },
      { fecha: '2024-12-15', texto: 'Inspección semestral OK', estado: 'ok' },
    ],
  },
  {
    id: '3',
    tag: '3113-10-00-11-GRP0001',
    nombre: 'Grupo electrógeno principal',
    tipo: 'Equipo industrial',
    capa: 'superficie',
    sector: 'superficie',
    lat: -46.8628,
    lng: -70.3275,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Sala de generación',
    inspector_asignado: 'L. Sánchez',
    ultima_inspeccion: '2025-04-20',
    proxima_inspeccion: '2025-07-20',
    checklist: [
      { descripcion: 'Nivel de aceite',            resultado: true },
      { descripcion: 'Batería de arranque',         resultado: true },
      { descripcion: 'Filtro de aire',              resultado: true },
      { descripcion: 'Refrigerante — nivel y pH',   resultado: true },
    ],
    historial: [
      { fecha: '2025-04-20', texto: 'Mantenimiento preventivo completo', estado: 'ok' },
      { fecha: '2025-01-18', texto: 'Inspección trimestral sin hallazgos', estado: 'ok' },
    ],
  },
  {
    id: '4',
    tag: '3113-10-00-11-BLG0005',
    nombre: 'Edificio Administración',
    tipo: 'Edificio',
    capa: 'superficie',
    sector: 'superficie',
    lat: -46.8622,
    lng: -70.3255,
    status: 'Operativo',
    estado: 'Óptimo',
    ubicacion: 'Sector administrativo',
    inspector_asignado: 'M. Rodríguez',
    ultima_inspeccion: '2025-02-28',
    proxima_inspeccion: '2025-08-28',
    checklist: [
      { descripcion: 'Estructura — fisuras o daños',          resultado: true },
      { descripcion: 'Instalación eléctrica',                  resultado: true },
      { descripcion: 'Sistema contra incendios — vigencia',    resultado: false, nota: 'Extintores vencen en junio 2025' },
      { descripcion: 'Vías de evacuación — señaladas y libres', resultado: true },
    ],
    historial: [
      { fecha: '2025-02-28', texto: 'Extintores próximos a vencer', estado: 'warn' },
      { fecha: '2024-08-15', texto: 'Inspección semestral aprobada', estado: 'ok' },
    ],
  },
  {
    id: '5',
    tag: '3113-10-00-11-PMP0003',
    nombre: 'Bomba de agua industrial #3',
    tipo: 'Bomba',
    capa: 'superficie',
    sector: 'superficie',
    lat: -46.8652,
    lng: -70.3280,
    status: 'Fuera de servicio',
    estado: 'Rotor bloqueado',
    ubicacion: 'Planta de agua',
    inspector_asignado: 'P. González',
    ultima_inspeccion: '2025-05-01',
    proxima_inspeccion: '2025-05-15',
    checklist: [
      { descripcion: 'Sellos mecánicos',    resultado: false, nota: 'Fuga visible en sello frontal' },
      { descripcion: 'Rodamientos',         resultado: false, nota: 'Ruido anormal detectado' },
      { descripcion: 'Acoplamiento',        resultado: true },
      { descripcion: 'Vibración — nivel',   resultado: false, nota: 'Supera ISO 10816 clase II' },
    ],
    historial: [
      { fecha: '2025-05-01', texto: 'Falla de sello — fuera de servicio', estado: 'warn' },
      { fecha: '2025-02-10', texto: 'Inspección rutinaria sin hallazgos',  estado: 'ok' },
    ],
  },
  // ── Subterráneo — Mariana Central ──
  {
    id: '6',
    tag: '3113-MC-NV450-PRT0001',
    nombre: 'Pórtico 450',
    tipo: 'Equipo de izaje',
    capa: 'subterraneo',
    sector: 'mariana_central',
    mina: 'mariana_central',
    ug_x: 581,
    ug_y: 455,
    status: 'Operativo',
    estado: 'Revisar en próximo PM',
    ubicacion: 'Estocada taller Nivel 450',
    inspector_asignado: 'C. Herrera',
    ultima_inspeccion: '2025-03-15',
    proxima_inspeccion: '2025-05-15',
    checklist: [
      { descripcion: 'Estructura — fisuras o deformaciones', resultado: true },
      { descripcion: 'Ruedas y rieles — desgaste',           resultado: false, nota: 'Desgaste leve en rueda delantera izquierda' },
      { descripcion: 'Frenos — funcionalidad',               resultado: true },
      { descripcion: 'Límites de carrera',                   resultado: false, nota: 'Pendiente verificación en próximo PM' },
      { descripcion: 'Placa de carga — legible y vigente',   resultado: true },
    ],
    historial: [
      { fecha: '2025-03-15', texto: 'Desgaste en rueda — monitorear', estado: 'warn' },
      { fecha: '2024-12-10', texto: 'Inspección ASME B30.2 — OK',     estado: 'ok' },
    ],
  },
  {
    id: '7',
    tag: '3113-MC-NV375-VEN0001',
    nombre: 'Ventilador principal NV375',
    tipo: 'Equipo industrial',
    capa: 'subterraneo',
    sector: 'mariana_central',
    mina: 'mariana_central',
    ug_x: 566,
    ug_y: 375,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Galería principal Nivel 375',
    inspector_asignado: 'C. Herrera',
    ultima_inspeccion: '2025-04-05',
    proxima_inspeccion: '2025-07-05',
    checklist: [
      { descripcion: 'Caudal de ventilación — medición',  resultado: true },
      { descripcion: 'Rodamientos — temperatura y ruido', resultado: true },
      { descripcion: 'Fijaciones al marco',               resultado: true },
      { descripcion: 'Motor eléctrico — aislación',       resultado: true },
    ],
    historial: [
      { fecha: '2025-04-05', texto: 'Inspección trimestral aprobada', estado: 'ok' },
      { fecha: '2025-01-10', texto: 'Reemplazo de rodamientos',       estado: 'ok' },
    ],
  },
  {
    id: '8',
    tag: '3113-MC-NV500-PMP0002',
    nombre: 'Bomba sumidero NV500',
    tipo: 'Bomba',
    capa: 'subterraneo',
    sector: 'mariana_central',
    mina: 'mariana_central',
    ug_x: 575,
    ug_y: 500,
    status: 'En mantenimiento',
    estado: 'Cambio de impulsor',
    ubicacion: 'Sumidero Nivel 500',
    inspector_asignado: 'A. Torres',
    ultima_inspeccion: '2025-04-28',
    proxima_inspeccion: '2025-05-10',
    checklist: [
      { descripcion: 'Impulsor — desgaste y cavitación', resultado: false, nota: 'Impulsor con erosión severa' },
      { descripcion: 'Carcasa — fisuras',                resultado: true },
      { descripcion: 'Sello mecánico',                   resultado: false, nota: 'Fuga leve detectada' },
      { descripcion: 'Motor — aislación',                resultado: true },
    ],
    historial: [
      { fecha: '2025-04-28', texto: 'Impulsor a reemplazar — en mantenimiento', estado: 'warn' },
      { fecha: '2025-01-20', texto: 'Inspección rutinaria OK',                  estado: 'ok' },
    ],
  },
  // ── Subterráneo — Mariana Norte ──
  {
    id: '9',
    tag: '3113-MN-NV400-VEN0001',
    nombre: 'Ventilador NV400',
    tipo: 'Equipo industrial',
    capa: 'subterraneo',
    sector: 'mariana_norte',
    mina: 'mariana_norte',
    ug_x: 22,
    ug_y: 400,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Galería principal Nivel 400',
    inspector_asignado: 'R. Navarro',
    ultima_inspeccion: '2025-04-12',
    proxima_inspeccion: '2025-07-12',
    checklist: [
      { descripcion: 'Caudal de ventilación', resultado: true },
      { descripcion: 'Rodamientos — temperatura', resultado: true },
      { descripcion: 'Motor eléctrico — aislación', resultado: true },
    ],
    historial: [
      { fecha: '2025-04-12', texto: 'Inspección trimestral aprobada', estado: 'ok' },
    ],
  },
  {
    id: '10',
    tag: '3113-MN-NV350-PMP0001',
    nombre: 'Bomba sumidero NV350',
    tipo: 'Bomba',
    capa: 'subterraneo',
    sector: 'mariana_norte',
    mina: 'mariana_norte',
    ug_x: 35,
    ug_y: 350,
    status: 'En mantenimiento',
    estado: 'Cambio de sellos',
    ubicacion: 'Sumidero Nivel 350',
    inspector_asignado: 'R. Navarro',
    ultima_inspeccion: '2025-05-02',
    proxima_inspeccion: '2025-05-20',
    checklist: [
      { descripcion: 'Impulsor — desgaste', resultado: true },
      { descripcion: 'Sello mecánico', resultado: false, nota: 'Fuga leve — en mantenimiento' },
      { descripcion: 'Motor — aislación', resultado: true },
    ],
    historial: [
      { fecha: '2025-05-02', texto: 'Sello a reemplazar', estado: 'warn' },
      { fecha: '2025-02-14', texto: 'Inspección semestral OK', estado: 'ok' },
    ],
  },
  {
    id: '11',
    tag: '3113-MN-NV480-PRT0001',
    nombre: 'Pórtico izaje NV480',
    tipo: 'Equipo de izaje',
    capa: 'subterraneo',
    sector: 'mariana_norte',
    mina: 'mariana_norte',
    ug_x: 12,
    ug_y: 480,
    status: 'Operativo',
    estado: 'Óptimo',
    ubicacion: 'Taller Nivel 480',
    inspector_asignado: 'R. Navarro',
    ultima_inspeccion: '2025-03-28',
    proxima_inspeccion: '2025-06-28',
    checklist: [
      { descripcion: 'Estructura — fisuras', resultado: true },
      { descripcion: 'Ruedas y rieles', resultado: true },
      { descripcion: 'Frenos', resultado: true },
      { descripcion: 'Placa de carga vigente', resultado: true },
    ],
    historial: [
      { fecha: '2025-03-28', texto: 'Inspección ASME B30.2 — OK', estado: 'ok' },
    ],
  },

  // ── Subterráneo — Emilia ──
  {
    id: '12',
    tag: '3113-EM-NV320-VEN0001',
    nombre: 'Ventilador principal Emilia',
    tipo: 'Equipo industrial',
    capa: 'subterraneo',
    sector: 'emilia',
    mina: 'emilia',
    ug_x: 25,
    ug_y: 320,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Acceso galería principal',
    inspector_asignado: 'F. Molina',
    ultima_inspeccion: '2025-04-18',
    proxima_inspeccion: '2025-07-18',
    checklist: [
      { descripcion: 'Caudal de ventilación', resultado: true },
      { descripcion: 'Rodamientos', resultado: true },
      { descripcion: 'Fijaciones al marco', resultado: false, nota: 'Perno flojo sector NE' },
    ],
    historial: [
      { fecha: '2025-04-18', texto: 'Perno flojo detectado — programar ajuste', estado: 'warn' },
      { fecha: '2025-01-22', texto: 'Inspección trimestral OK', estado: 'ok' },
    ],
  },
  {
    id: '13',
    tag: '3113-EM-NV280-PMP0001',
    nombre: 'Bomba sumidero NV280',
    tipo: 'Bomba',
    capa: 'subterraneo',
    sector: 'emilia',
    mina: 'emilia',
    ug_x: 38,
    ug_y: 280,
    status: 'Fuera de servicio',
    estado: 'Impulsor bloqueado',
    ubicacion: 'Sumidero Nivel 280',
    inspector_asignado: 'F. Molina',
    ultima_inspeccion: '2025-04-30',
    proxima_inspeccion: '2025-05-12',
    checklist: [
      { descripcion: 'Impulsor — desgaste', resultado: false, nota: 'Bloqueo por cuerpo extraño' },
      { descripcion: 'Sello mecánico', resultado: false, nota: 'Fuga severa' },
      { descripcion: 'Motor — aislación', resultado: true },
    ],
    historial: [
      { fecha: '2025-04-30', texto: 'Fuera de servicio — impulsor bloqueado', estado: 'warn' },
      { fecha: '2025-01-10', texto: 'Mantenimiento preventivo completo', estado: 'ok' },
    ],
  },
  {
    id: '14',
    tag: '3113-EM-NV400-COM0001',
    nombre: 'Compresor de aire NV400',
    tipo: 'Compresor',
    capa: 'subterraneo',
    sector: 'emilia',
    mina: 'emilia',
    ug_x: 30,
    ug_y: 400,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Sala de compresores Nivel 400',
    inspector_asignado: 'F. Molina',
    ultima_inspeccion: '2025-03-10',
    proxima_inspeccion: '2025-06-10',
    checklist: [
      { descripcion: 'Presión de trabajo', resultado: true },
      { descripcion: 'Filtros de aire', resultado: true },
      { descripcion: 'Válvulas de seguridad', resultado: true },
      { descripcion: 'Nivel de aceite', resultado: true },
    ],
    historial: [
      { fecha: '2025-03-10', texto: 'Mantenimiento trimestral OK', estado: 'ok' },
    ],
  },

  // ── Subterráneo — San Marcos ──
  {
    id: '15',
    tag: '3113-SM-NV360-VEN0001',
    nombre: 'Ventilador NV360',
    tipo: 'Equipo industrial',
    capa: 'subterraneo',
    sector: 'san_marcos',
    mina: 'san_marcos',
    ug_x: 20,
    ug_y: 360,
    status: 'Operativo',
    estado: 'Óptimo',
    ubicacion: 'Galería este Nivel 360',
    inspector_asignado: 'H. Castro',
    ultima_inspeccion: '2025-04-25',
    proxima_inspeccion: '2025-07-25',
    checklist: [
      { descripcion: 'Caudal de ventilación', resultado: true },
      { descripcion: 'Rodamientos', resultado: true },
      { descripcion: 'Fijaciones al marco', resultado: true },
    ],
    historial: [
      { fecha: '2025-04-25', texto: 'Inspección trimestral aprobada', estado: 'ok' },
    ],
  },
  {
    id: '16',
    tag: '3113-SM-NV420-PMP0001',
    nombre: 'Bomba principal NV420',
    tipo: 'Bomba',
    capa: 'subterraneo',
    sector: 'san_marcos',
    mina: 'san_marcos',
    ug_x: 32,
    ug_y: 420,
    status: 'Operativo',
    estado: 'Normal',
    ubicacion: 'Sumidero Nivel 420',
    inspector_asignado: 'H. Castro',
    ultima_inspeccion: '2025-04-05',
    proxima_inspeccion: '2025-07-05',
    checklist: [
      { descripcion: 'Impulsor — desgaste', resultado: true },
      { descripcion: 'Sello mecánico', resultado: true },
      { descripcion: 'Motor — temperatura', resultado: true },
    ],
    historial: [
      { fecha: '2025-04-05', texto: 'Inspección rutinaria OK', estado: 'ok' },
      { fecha: '2025-01-08', texto: 'Mantenimiento semestral completo', estado: 'ok' },
    ],
  },
  {
    id: '17',
    tag: '3113-SM-NV500-PRT0001',
    nombre: 'Pórtico izaje NV500',
    tipo: 'Equipo de izaje',
    capa: 'subterraneo',
    sector: 'san_marcos',
    mina: 'san_marcos',
    ug_x: 27,
    ug_y: 500,
    status: 'En mantenimiento',
    estado: 'Cambio de ruedas',
    ubicacion: 'Taller Nivel 500',
    inspector_asignado: 'H. Castro',
    ultima_inspeccion: '2025-05-03',
    proxima_inspeccion: '2025-05-17',
    checklist: [
      { descripcion: 'Estructura — fisuras', resultado: true },
      { descripcion: 'Ruedas y rieles', resultado: false, nota: 'Rueda trasera derecha — desgaste severo' },
      { descripcion: 'Frenos', resultado: true },
    ],
    historial: [
      { fecha: '2025-05-03', texto: 'Rueda a reemplazar — en taller', estado: 'warn' },
      { fecha: '2025-02-20', texto: 'Inspección ASME B30.2 — OK', estado: 'ok' },
    ],
  },
]
