// POST /api/manuals/process
// Downloads the file from Supabase Storage, extracts text, chunks it with
// contextual enrichment, and saves to DB.
// FTS tsvector is auto-generated by PostgreSQL — no external embedding API needed.

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import Anthropic from '@anthropic-ai/sdk'
import { chunkText } from '@/lib/manuals/chunker'

export const dynamic = 'force-dynamic'
export const maxDuration = 60  // Vercel: allow up to 60s for processing

function getAnthropic() {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY no configurada')
  return new Anthropic({ apiKey })
}

export async function POST(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'No autorizado' }, { status: 401 })

  let body: { manualId: string }
  try { body = await request.json() } catch {
    return NextResponse.json({ error: 'Payload inválido' }, { status: 400 })
  }

  const admin = createAdminClient()

  // 1. Load manual metadata
  const { data: manual, error: mErr } = await admin
    .from('manuals')
    .select('*')
    .eq('id', body.manualId)
    .single()

  if (mErr || !manual) return NextResponse.json({ error: 'Manual no encontrado' }, { status: 404 })

  // 2. Download file from Supabase Storage
  const { data: fileData, error: dlErr } = await admin.storage
    .from('manuals')
    .download(manual.storage_path)

  if (dlErr || !fileData) {
    return NextResponse.json({ error: 'Error al descargar archivo' }, { status: 500 })
  }

  const buffer = Buffer.from(await fileData.arrayBuffer())

  // 3. Extract text based on format
  let rawText = ''
  try {
    rawText = await extractText(buffer, manual.formato, manual.nombre)
  } catch (e) {
    console.error('[Process] text extraction error:', e)
    return NextResponse.json({ error: 'Error al extraer texto del documento' }, { status: 500 })
  }

  if (!rawText.trim()) {
    return NextResponse.json({ error: 'No se pudo extraer texto del documento' }, { status: 422 })
  }

  // 4. Chunk with contextual enrichment
  const meta = {
    nombre:     manual.nombre,
    tipoActivo: manual.tipo_activo,
    fabricante: manual.fabricante,
    tipoDoc:    manual.tipo_doc,
  }
  const chunks = chunkText(rawText, meta)

  // 5. Delete existing chunks (re-processing case) then insert new ones
  await admin.from('manual_chunks').delete().eq('manual_id', body.manualId)

  // Insert in batches of 50 — tsvector is computed automatically by Postgres
  const BATCH = 50
  let savedCount = 0

  for (let i = 0; i < chunks.length; i += BATCH) {
    const batch = chunks.slice(i, i + BATCH)
    const rows = batch.map((chunk) => ({
      manual_id:    body.manualId,
      section_path: chunk.sectionPath,
      chunk_index:  chunk.chunkIndex,
      content:      chunk.content,
      context:      chunk.context,
      // tsv is GENERATED ALWAYS — no need to insert it
    }))

    const { error: insertErr } = await admin.from('manual_chunks').insert(rows)
    if (insertErr) {
      console.error('[Process] chunk insert error:', insertErr)
      continue
    }
    savedCount += rows.length
  }

  // 6. Mark manual as processed
  await admin
    .from('manuals')
    .update({ procesado: true, chunk_count: savedCount })
    .eq('id', body.manualId)

  return NextResponse.json({ ok: true, chunks: savedCount })
}

// ── Text extraction ───────────────────────────────────────────────────────────

async function extractText(buffer: Buffer, formato: string, nombre: string): Promise<string> {
  if (formato === 'txt') {
    return buffer.toString('utf-8')
  }

  if (formato === 'pdf') {
    const pdfParse = ((await import('pdf-parse')) as unknown as { default: (b: Buffer) => Promise<{ text: string }> }).default
    const data = await pdfParse(buffer)
    return data.text
  }

  if (formato === 'imagen') {
    // Use Claude vision to extract text from technical document image
    const base64 = buffer.toString('base64')
    const mediaType = nombre.toLowerCase().endsWith('.png')
      ? 'image/png'
      : nombre.toLowerCase().endsWith('.gif')
      ? 'image/gif'
      : 'image/jpeg'

    const response = await getAnthropic().messages.create({
      model:      'claude-haiku-4-5',
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: [
          {
            type: 'image',
            source: { type: 'base64', media_type: mediaType, data: base64 },
          },
          {
            type: 'text',
            text: 'Extractá todo el texto de esta imagen de documento técnico de mantenimiento industrial. Preservá los encabezados de sección, números, especificaciones técnicas y términos OEM exactamente como aparecen. Usá saltos de párrafo doble entre secciones distintas.',
          },
        ],
      }],
    })

    return response.content[0].type === 'text' ? response.content[0].text : ''
  }

  return ''
}
